namespace ERP.Persistence.Migrations;

public sealed class V001CreateCatalogAndInventory : IMigration
{
    public int Version => 1;

    public string Name => "Create catalog, inventory and audit tables";

    public IReadOnlyList<string> Statements { get; } =
    [
        """
        CREATE TABLE CATEGORY (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            PARENT_ID CHAR(36) CHARACTER SET ASCII,
            PARENT_KEY CHAR(36) CHARACTER SET ASCII NOT NULL,
            NAME VARCHAR(120) CHARACTER SET UTF8 NOT NULL,
            SORT_ORDER INTEGER NOT NULL CHECK (SORT_ORDER >= 0),
            STATUS SMALLINT NOT NULL,
            VIS_POS BOOLEAN NOT NULL,
            VIS_ONLINE BOOLEAN NOT NULL,
            VIS_PURCHASING BOOLEAN NOT NULL,
            CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (ID),
            CONSTRAINT UQ_CATEGORY_LEVEL_NAME UNIQUE (PARENT_KEY, NAME)
        )
        """,
        """
        CREATE TABLE PRODUCT_UNIT (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            NAME VARCHAR(60) CHARACTER SET UTF8 NOT NULL,
            SYMBOL VARCHAR(12) CHARACTER SET UTF8 NOT NULL,
            ALLOWS_FRACTIONS BOOLEAN NOT NULL,
            CONSTRAINT UQ_PRODUCT_UNIT_NAME UNIQUE (NAME),
            CONSTRAINT UQ_PRODUCT_UNIT_SYMBOL UNIQUE (SYMBOL)
        )
        """,
        """
        CREATE TABLE PRODUCT (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            NAME VARCHAR(200) CHARACTER SET UTF8 NOT NULL,
            SKU VARCHAR(64) CHARACTER SET UTF8,
            CATEGORY_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            BASE_UNIT_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            SALE_PRICE_RIALS BIGINT NOT NULL CHECK (SALE_PRICE_RIALS >= 0),
            STATUS SMALLINT NOT NULL,
            CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
            CONSTRAINT FK_PRODUCT_UNIT FOREIGN KEY (BASE_UNIT_ID) REFERENCES PRODUCT_UNIT (ID),
            CONSTRAINT UQ_PRODUCT_SKU UNIQUE (SKU)
        )
        """,
        """
        CREATE TABLE PRODUCT_BARCODE (
            PRODUCT_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            BARCODE VARCHAR(64) CHARACTER SET ASCII NOT NULL,
            CONSTRAINT PK_PRODUCT_BARCODE PRIMARY KEY (PRODUCT_ID, BARCODE),
            CONSTRAINT UQ_PRODUCT_BARCODE UNIQUE (BARCODE),
            CONSTRAINT FK_BARCODE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
        )
        """,
        """
        CREATE TABLE INVENTORY_LAYER (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            PRODUCT_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            WAREHOUSE_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            ORIGINAL_QTY DECIMAL(18, 3) NOT NULL CHECK (ORIGINAL_QTY > 0),
            REMAINING_QTY DECIMAL(18, 3) NOT NULL CHECK (REMAINING_QTY >= 0),
            UNIT_COST_RIALS BIGINT NOT NULL CHECK (UNIT_COST_RIALS >= 0),
            RECEIVED_ON DATE NOT NULL,
            CONSTRAINT FK_LAYER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
        )
        """,
        """
        CREATE TABLE STOCK_MOVEMENT (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            PRODUCT_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            WAREHOUSE_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            MOVEMENT_TYPE SMALLINT NOT NULL,
            QUANTITY DECIMAL(18, 3) NOT NULL CHECK (QUANTITY > 0),
            SOURCE_REFERENCE VARCHAR(120) CHARACTER SET UTF8 NOT NULL,
            OCCURRED_AT_UTC TIMESTAMP NOT NULL,
            CONSTRAINT FK_MOVEMENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
        )
        """,
        """
        CREATE TABLE AUDIT_ENTRY (
            ID CHAR(36) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
            ACTOR_USER_ID CHAR(36) CHARACTER SET ASCII NOT NULL,
            ACTION_NAME VARCHAR(120) CHARACTER SET ASCII NOT NULL,
            ENTITY_TYPE VARCHAR(120) CHARACTER SET ASCII NOT NULL,
            ENTITY_ID VARCHAR(120) CHARACTER SET ASCII NOT NULL,
            OLD_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
            NEW_VALUE BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
            OCCURRED_AT_UTC TIMESTAMP NOT NULL
        )
        """,
        "CREATE INDEX IX_CATEGORY_PARENT_SORT ON CATEGORY (PARENT_ID, SORT_ORDER)",
        "CREATE INDEX IX_PRODUCT_NAME ON PRODUCT (NAME)",
        "CREATE INDEX IX_LAYER_PRODUCT_WAREHOUSE ON INVENTORY_LAYER (PRODUCT_ID, WAREHOUSE_ID)",
        "CREATE INDEX IX_MOVEMENT_PRODUCT_WAREHOUSE ON STOCK_MOVEMENT (PRODUCT_ID, WAREHOUSE_ID)",
    ];
}
